### PR TITLE
Full api3

### PR DESCRIPTION
**Pull request by metaron-uk**
@ryangribble 
I've created this 'personal' pull request to give you a chance to check you're OK with my rebased versions of your commits before I go 'public'.
(Didn't want to play fast and loose with your commits without your say so!)

### CODE REVIEW

**Comment by ryangribble** [comment]
Apart from the 1 mentioned thing and 1 possible space vs tabs issue, it all looks great to me!

In terms of adapting addons let me know if you want some help.  Obviously i will take care of pvr.wmc so you dont have to worry about that, but if you want help doing some of the other ones let me know (perhaps if you do 1 so I can see what you want done then we can split up the remaining ones).  

Also I noticed that the addon includes on kodi side can now specify a branch name rather than a commit so when doing the Kodi side includes its probably a good idea to set them all to "master" rather than a specific hash

**Comment by metaron-uk** [comment]
I've fixed the whitespace issue (it was a tab) and amended the comment on maxRecordings - I think it should meet both ksooo's purpose and ours. Will force push here after lunch.
Thanks for the offer of help and the pointer about 'master' versions. I'll definitely take you up on that.

**Lifetime**
There is a bit of a problem with iLifetime. wmc and mythtv are using it as _recording_ lifetime, it seems (from the old comment in the include file) that tvheadend is using it as _timer_ lifetime.
I can see this being a bit of a sticking point.

Currently I've removed the word 'timer' from the description, but that just puts the problem off until later. We could add a flag 'PVR_TIMER_SUPPORTS_RECORDING_LIFETIME' which is declared mutually exclusive with 'PVR_TIMER_SUPPORTS_TIMER_LIFETIME' (i.e. re-name the existing flag) and uses the same variables? Otherwise we really are mixing our drinks between addons. 

It seems overkill to create another set of iRecordingLifetime definitions now (as wmc and myth could just re-use the existing definitions), but it might come to that :-(....
What do you think?

**Comment by ryangribble** [comment]
not sure on the lifetime stuff, I just dont see it as that big of a deal whether its a timer lifetime or a recording lifetime.  The fact that it was already merged into Kodi 16 makes me feel like its not your job in API 3.0.0 to address that... you are adding enhancements/suggestions rather than clearing up confusion that previously accepted/merged PR created

**Comment by metaron-uk** [comment]
:-)

**Comment by metaron-uk** [comment]
@ryangribble 
I've rebased with further clarifications to the commit messages and an extra 'fixup' for compatibility code menu visibility. Moving discussion back to main PR.

**Pull request closed without merging**
